Documentation Update
dhlab-basel/JourneyStar pull request #15
Opened 2024-09-07 11:31 UTC by Nora-Olivia-Ammann

2024-09-07 11:34 UTC, Nora-Olivia-Ammann commented on index.markdown
Currently the images use the old prefix `trip-onto`. That should be updated to `js`. The graphml files are not here correct? @SepidehAlassi

2024-09-07 12:06 UTC, Nora-Olivia-Ammann commented on journeyStar.ttl
> -@prefix currency: <https://spec.edmcouncil.org/fibo/ontology/FND/Accounting/ISO4217-CurrencyCodes/>.
These prefixes are not used

2024-09-07 12:06 UTC, Nora-Olivia-Ammann commented on journeyStar.ttl
> -js:Event rdf:type owl:Class ;
I grouped the classes and properties based on sub-classing and sub-properties.

2024-09-07 12:06 UTC, Nora-Olivia-Ammann commented on journeyStar_shacl.ttl
> +        sh:minCount 1;
Consistent ordering of types of properties

2024-09-07 12:06 UTC, Nora-Olivia-Ammann commented on journeyStar.ttl
> +
consistent spacing

2024-09-07 12:07 UTC, Nora-Olivia-Ammann commented on journeyStar_shacl.ttl
>  @prefix js-shacl: <http://journey-star.dhlab.unibas.ch/shacl/trip-shacl#> .
I would suggest to change the namespace to `journey-shacl` for consistency's sake

2024-09-18 08:39 UTC, SepidehAlassi requested changes
Please remove the `#` from end of class and property URLs, they can cause confusion. Then it is good to go

2024-09-18 08:39 UTC, SepidehAlassi commented on journeyStar.ttl
> +# http://journey-star.dhlab.unibas.ch/ontology/JourneyStar#SightSeeing #
remove the ` #` from the end of all URLs put in comments

2024-09-18 09:11 UTC, SepidehAlassi commented on index.markdown
yes, graphml file are old. They should be removed from the repo, and the images in docs should be updated.

2024-09-18 09:12 UTC, SepidehAlassi commented on journeyStar_shacl.ttl
>  @prefix js-shacl: <http://journey-star.dhlab.unibas.ch/shacl/trip-shacl#> .
yes, it should be corrected.

2024-09-21 06:10 UTC, Nora-Olivia-Ammann commented on index.markdown
Do you still have the files? Because I think it would be fasted to fix the old ones.

2024-09-23 18:19 UTC, merged